### PR TITLE
Adding ERC6551 Demo + Has XMTP functionality

### PR DESCRIPTION
**Pull request by YosephKS**
# New Features
- New section for getting all NFTs by 0x address or Lens and their ERC6551 account + NFT holdings in the ERC6551 account
- Check if XMTP is enabled in resolving social profile section

# Test input
- Try either `windle.eth` or `0xcf94ba8779848141d685d44452c975c2ddc04945` for testing ERC6551 account

# What's Left
- Fixing UI bug crash on Enhancement section, missing optional chaining
- Modify `GetNFTHolders` query to also query Polygon instead of Ethereum only

### CODE REVIEW

**Comment by dabit3** [comment]
Hi @YosephKS is this one ready to merge?

**Comment by YosephKS** [comment]
Hey @dabit3 not yet, I'll let you know once it's ready!

Just need to make a few more commits, should be done by today

**Comment by YosephKS** [comment]
Alright @dabit3 feel free to review it anytime 😄

**Comment by dabit3** [comment]
Nice pr @YosephKS thank you 🙏

**Pull request merged**
